package com.example.demo.domain;

import java.util.Date;

public class MpUserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mp_user_info.id
     *
     * @mbggenerated Sat Jul 14 02:22:30 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mp_user_info.openId
     *
     * @mbggenerated Sat Jul 14 02:22:30 CST 2018
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mp_user_info.nickName
     *
     * @mbggenerated Sat Jul 14 02:22:30 CST 2018
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mp_user_info.unionId
     *
     * @mbggenerated Sat Jul 14 02:22:30 CST 2018
     */
    private String unionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mp_user_info.createTime
     *
     * @mbggenerated Sat Jul 14 02:22:30 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mp_user_info.updatetime
     *
     * @mbggenerated Sat Jul 14 02:22:30 CST 2018
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mp_user_info.id
     *
     * @return the value of mp_user_info.id
     *
     * @mbggenerated Sat Jul 14 02:22:30 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mp_user_info.id
     *
     * @param id the value for mp_user_info.id
     *
     * @mbggenerated Sat Jul 14 02:22:30 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mp_user_info.openId
     *
     * @return the value of mp_user_info.openId
     *
     * @mbggenerated Sat Jul 14 02:22:30 CST 2018
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mp_user_info.openId
     *
     * @param openId the value for mp_user_info.openId
     *
     * @mbggenerated Sat Jul 14 02:22:30 CST 2018
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mp_user_info.nickName
     *
     * @return the value of mp_user_info.nickName
     *
     * @mbggenerated Sat Jul 14 02:22:30 CST 2018
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mp_user_info.nickName
     *
     * @param nickName the value for mp_user_info.nickName
     *
     * @mbggenerated Sat Jul 14 02:22:30 CST 2018
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mp_user_info.unionId
     *
     * @return the value of mp_user_info.unionId
     *
     * @mbggenerated Sat Jul 14 02:22:30 CST 2018
     */
    public String getUnionId() {
        return unionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mp_user_info.unionId
     *
     * @param unionId the value for mp_user_info.unionId
     *
     * @mbggenerated Sat Jul 14 02:22:30 CST 2018
     */
    public void setUnionId(String unionId) {
        this.unionId = unionId == null ? null : unionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mp_user_info.createTime
     *
     * @return the value of mp_user_info.createTime
     *
     * @mbggenerated Sat Jul 14 02:22:30 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mp_user_info.createTime
     *
     * @param createTime the value for mp_user_info.createTime
     *
     * @mbggenerated Sat Jul 14 02:22:30 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mp_user_info.updatetime
     *
     * @return the value of mp_user_info.updatetime
     *
     * @mbggenerated Sat Jul 14 02:22:30 CST 2018
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mp_user_info.updatetime
     *
     * @param updatetime the value for mp_user_info.updatetime
     *
     * @mbggenerated Sat Jul 14 02:22:30 CST 2018
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}