package com.example.demo.domain;

import java.util.Date;

public class ShuiDiChou {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shuidichou.id
     *
     * @mbggenerated Fri Nov 23 16:31:34 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shuidichou.imgHead
     *
     * @mbggenerated Fri Nov 23 16:31:34 CST 2018
     */
    private String imgHead;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shuidichou.nickname
     *
     * @mbggenerated Fri Nov 23 16:31:34 CST 2018
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shuidichou.money
     *
     * @mbggenerated Fri Nov 23 16:31:34 CST 2018
     */
    private Integer money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shuidichou.createTime
     *
     * @mbggenerated Fri Nov 23 16:31:34 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shuidichou.comment
     *
     * @mbggenerated Fri Nov 23 16:31:34 CST 2018
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shuidichou.id
     *
     * @return the value of shuidichou.id
     *
     * @mbggenerated Fri Nov 23 16:31:34 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shuidichou.id
     *
     * @param id the value for shuidichou.id
     *
     * @mbggenerated Fri Nov 23 16:31:34 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shuidichou.imgHead
     *
     * @return the value of shuidichou.imgHead
     *
     * @mbggenerated Fri Nov 23 16:31:34 CST 2018
     */
    public String getImgHead() {
        return imgHead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shuidichou.imgHead
     *
     * @param imgHead the value for shuidichou.imgHead
     *
     * @mbggenerated Fri Nov 23 16:31:34 CST 2018
     */
    public void setImgHead(String imgHead) {
        this.imgHead = imgHead == null ? null : imgHead.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shuidichou.nickname
     *
     * @return the value of shuidichou.nickname
     *
     * @mbggenerated Fri Nov 23 16:31:34 CST 2018
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shuidichou.nickname
     *
     * @param nickname the value for shuidichou.nickname
     *
     * @mbggenerated Fri Nov 23 16:31:34 CST 2018
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shuidichou.money
     *
     * @return the value of shuidichou.money
     *
     * @mbggenerated Fri Nov 23 16:31:34 CST 2018
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shuidichou.money
     *
     * @param money the value for shuidichou.money
     *
     * @mbggenerated Fri Nov 23 16:31:34 CST 2018
     */
    public void setMoney(Integer money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shuidichou.createTime
     *
     * @return the value of shuidichou.createTime
     *
     * @mbggenerated Fri Nov 23 16:31:34 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shuidichou.createTime
     *
     * @param createTime the value for shuidichou.createTime
     *
     * @mbggenerated Fri Nov 23 16:31:34 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shuidichou.comment
     *
     * @return the value of shuidichou.comment
     *
     * @mbggenerated Fri Nov 23 16:31:34 CST 2018
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shuidichou.comment
     *
     * @param comment the value for shuidichou.comment
     *
     * @mbggenerated Fri Nov 23 16:31:34 CST 2018
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}