package com.example.demo.domain;

import java.util.Date;

public class SysRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.id
     *
     * @mbggenerated Thu Jul 04 16:39:14 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.created_at
     *
     * @mbggenerated Thu Jul 04 16:39:14 CST 2019
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.updated_at
     *
     * @mbggenerated Thu Jul 04 16:39:14 CST 2019
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.name
     *
     * @mbggenerated Thu Jul 04 16:39:14 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.intro
     *
     * @mbggenerated Thu Jul 04 16:39:14 CST 2019
     */
    private String intro;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.id
     *
     * @return the value of sys_role.id
     *
     * @mbggenerated Thu Jul 04 16:39:14 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.id
     *
     * @param id the value for sys_role.id
     *
     * @mbggenerated Thu Jul 04 16:39:14 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.created_at
     *
     * @return the value of sys_role.created_at
     *
     * @mbggenerated Thu Jul 04 16:39:14 CST 2019
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.created_at
     *
     * @param createdAt the value for sys_role.created_at
     *
     * @mbggenerated Thu Jul 04 16:39:14 CST 2019
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.updated_at
     *
     * @return the value of sys_role.updated_at
     *
     * @mbggenerated Thu Jul 04 16:39:14 CST 2019
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.updated_at
     *
     * @param updatedAt the value for sys_role.updated_at
     *
     * @mbggenerated Thu Jul 04 16:39:14 CST 2019
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.name
     *
     * @return the value of sys_role.name
     *
     * @mbggenerated Thu Jul 04 16:39:14 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.name
     *
     * @param name the value for sys_role.name
     *
     * @mbggenerated Thu Jul 04 16:39:14 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.intro
     *
     * @return the value of sys_role.intro
     *
     * @mbggenerated Thu Jul 04 16:39:14 CST 2019
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.intro
     *
     * @param intro the value for sys_role.intro
     *
     * @mbggenerated Thu Jul 04 16:39:14 CST 2019
     */
    public void setIntro(String intro) {
        this.intro = intro == null ? null : intro.trim();
    }
}