package com.example.demo.domain;

import java.util.Date;

public class SysUserRoleMap {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role_map.id
     *
     * @mbggenerated Thu Jul 04 16:39:14 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role_map.created_at
     *
     * @mbggenerated Thu Jul 04 16:39:14 CST 2019
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role_map.suid
     *
     * @mbggenerated Thu Jul 04 16:39:14 CST 2019
     */
    private Long suid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role_map.srid
     *
     * @mbggenerated Thu Jul 04 16:39:14 CST 2019
     */
    private Long srid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role_map.id
     *
     * @return the value of sys_user_role_map.id
     *
     * @mbggenerated Thu Jul 04 16:39:14 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role_map.id
     *
     * @param id the value for sys_user_role_map.id
     *
     * @mbggenerated Thu Jul 04 16:39:14 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role_map.created_at
     *
     * @return the value of sys_user_role_map.created_at
     *
     * @mbggenerated Thu Jul 04 16:39:14 CST 2019
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role_map.created_at
     *
     * @param createdAt the value for sys_user_role_map.created_at
     *
     * @mbggenerated Thu Jul 04 16:39:14 CST 2019
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role_map.suid
     *
     * @return the value of sys_user_role_map.suid
     *
     * @mbggenerated Thu Jul 04 16:39:14 CST 2019
     */
    public Long getSuid() {
        return suid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role_map.suid
     *
     * @param suid the value for sys_user_role_map.suid
     *
     * @mbggenerated Thu Jul 04 16:39:14 CST 2019
     */
    public void setSuid(Long suid) {
        this.suid = suid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role_map.srid
     *
     * @return the value of sys_user_role_map.srid
     *
     * @mbggenerated Thu Jul 04 16:39:14 CST 2019
     */
    public Long getSrid() {
        return srid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role_map.srid
     *
     * @param srid the value for sys_user_role_map.srid
     *
     * @mbggenerated Thu Jul 04 16:39:14 CST 2019
     */
    public void setSrid(Long srid) {
        this.srid = srid;
    }
}