package com.example.demo.dao;

import com.example.demo.domain.ShuiDiChou;

public interface ShuiDiChouMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shuidichou
     *
     * @mbggenerated Fri Nov 23 16:31:34 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shuidichou
     *
     * @mbggenerated Fri Nov 23 16:31:34 CST 2018
     */
    int insert(ShuiDiChou record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shuidichou
     *
     * @mbggenerated Fri Nov 23 16:31:34 CST 2018
     */
    int insertSelective(ShuiDiChou record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shuidichou
     *
     * @mbggenerated Fri Nov 23 16:31:34 CST 2018
     */
    ShuiDiChou selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shuidichou
     *
     * @mbggenerated Fri Nov 23 16:31:34 CST 2018
     */
    int updateByPrimaryKeySelective(ShuiDiChou record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shuidichou
     *
     * @mbggenerated Fri Nov 23 16:31:34 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(ShuiDiChou record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shuidichou
     *
     * @mbggenerated Fri Nov 23 16:31:34 CST 2018
     */
    int updateByPrimaryKey(ShuiDiChou record);
}