package com.example.demo.dao;

import com.example.demo.domain.SysUserRoleMap;
import com.example.demo.domain.SysUserRoleMapExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysUserRoleMapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role_map
     *
     * @mbggenerated Thu Jul 04 16:39:14 CST 2019
     */
    int countByExample(SysUserRoleMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role_map
     *
     * @mbggenerated Thu Jul 04 16:39:14 CST 2019
     */
    int deleteByExample(SysUserRoleMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role_map
     *
     * @mbggenerated Thu Jul 04 16:39:14 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role_map
     *
     * @mbggenerated Thu Jul 04 16:39:14 CST 2019
     */
    int insert(SysUserRoleMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role_map
     *
     * @mbggenerated Thu Jul 04 16:39:14 CST 2019
     */
    int insertSelective(SysUserRoleMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role_map
     *
     * @mbggenerated Thu Jul 04 16:39:14 CST 2019
     */
    List<SysUserRoleMap> selectByExample(SysUserRoleMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role_map
     *
     * @mbggenerated Thu Jul 04 16:39:14 CST 2019
     */
    SysUserRoleMap selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role_map
     *
     * @mbggenerated Thu Jul 04 16:39:14 CST 2019
     */
    int updateByExampleSelective(@Param("record") SysUserRoleMap record, @Param("example") SysUserRoleMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role_map
     *
     * @mbggenerated Thu Jul 04 16:39:14 CST 2019
     */
    int updateByExample(@Param("record") SysUserRoleMap record, @Param("example") SysUserRoleMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role_map
     *
     * @mbggenerated Thu Jul 04 16:39:14 CST 2019
     */
    int updateByPrimaryKeySelective(SysUserRoleMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role_map
     *
     * @mbggenerated Thu Jul 04 16:39:14 CST 2019
     */
    int updateByPrimaryKey(SysUserRoleMap record);
}